jms.send:
  enable: true
  sessionFactory:
    cacheSize: 1

# @EnableTracing in SpringCloudMicroSetup explicitly turns on ZipkinAutoConfiguration, so it sort of stops being AUTO 
# configuration and it's @AutoConfigureBefore(TraceAutoConfiguration.class) starts to be ignored, and we start to get 
# an exception, that there are two SpanReporter in the context and so it can't be autowired
# 
# Another thing - we don't have Zipkin in our infrastructure yet. 
# 
spring.zipkin.enabled: false
